const GET_SIZE_IMAGE_REQUEST = "GET_SIZE_IMAGE_REQUEST";
const GET_SIZE_IMAGE_SUCCESS = "GET_SIZE_IMAGE_SUCCESS";
const GET_SIZE_IMAGE_ERROR = "GET_SIZE_IMAGE_ERROR";

export {
    GET_SIZE_IMAGE_REQUEST,
    GET_SIZE_IMAGE_SUCCESS,
    GET_SIZE_IMAGE_ERROR
}