const INFO_IMAGE_REQUEST = "INFO_IMAGE_REQUEST";
const INFO_IMAGE_SUCCESS = "INFO_IMAGE_SUCCESS";
const INFO_IMAGE_ERROR = "INFO_IMAGE_ERROR";

export {
    INFO_IMAGE_REQUEST,
    INFO_IMAGE_SUCCESS,
    INFO_IMAGE_ERROR
}