const SEARCH_IMAGE_REQUEST = "SEARCH_IMAGE_REQUEST";
const SEARCH_IMAGE_SUCCESS = "SEARCH_IMAGE_SUCCESS";
const SEARCH_IMAGE_ERROR = "SEARCH_IMAGE_ERROR";

export {
    SEARCH_IMAGE_REQUEST,
    SEARCH_IMAGE_SUCCESS,
    SEARCH_IMAGE_ERROR
    }